Added Checklist and Known Issues section
dpc-sdp/sdp-docs pull request #24
Opened 2021-10-06 01:37 UTC by edyuenyw

Added initial changes for https://digital-engagement.atlassian.net/browse/SDPA-5804

2021-10-06 01:50 UTC, anthony-malkoun requested changes
Hi @edyuenyw see my comments about getting these changes into the `docs` directory.

2021-10-06 01:50 UTC, anthony-malkoun commented on README.md
> +
As discussed @edyuenyw `README.md` is about setting up the `dpc-sdp/sdp-docs` project, not about setting up the reference site. Everything under the `docs` directory in this project gets deployed (eventually) to https://dpc-sdp.github.io/sdp-docs/ so your changes should live under there. Thinking about this I'm thinking a new page under the `docs/working-with-sdp.md` for anything DPC/Cenitex specific and add to `docs/working-with-sdp.md` for other steps. Thoughts?

2021-10-06 04:47 UTC, edyuenyw commented on README.md
> +
@anthony-malkoun I've made further changes and add more details to my commit. I also "reverted" the README.md commit which I still can see it in my log though there was not changed made to README.md anymore.
Can you please check and let me know if I need to change anything else?

2021-10-12 01:27 UTC, anthony-malkoun requested changes
Hi @edyuenyw can you update your build to use pygmy-go and document? I think there's value in creating a subpage on this for DPC/Cenitex with issues. You can create in this PR or create a new one if you prefer

2021-12-15 06:45 UTC, anthony-malkoun requested changes
Hi @edyuenyw most of the changes are small grammar/spelling issues. There are a few bigger changes I'd like to see. Let me know if you need more detail.

2021-12-15 06:45 UTC, anthony-malkoun commented on mkdocs.yml
> +  - Troubleshooting: troubleshooting.md
I think this should be a subpage of the `working-with-sdp.md` page. Just indent (see Bay: below)

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> + This page provides some workaround for issues that you may encounter during a local build.
*workarounds

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +Unable to install software (e.g Docker Desktop) or run commands which requires elevated permissions.
*require

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +3. Check again to see if you have the elevated permissions or not. You might have restart your computer several times to take effect.
*have to restart

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +## SSH Key
Delete if no issues.

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +*(Remote work)* Unable to resolve host or cannot descrypt encoded SSH
*decrypt

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/working-with-sdp.md
> +- [Generate new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) will guide you on how to generate, test and a
Did the instruction specify a different key type then `id_rsa`? If so don't we need to make a note to only use `id_rsa` and not the suggested one?

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/working-with-sdp.md
> +    ```
Please explain the differences between `ahoy build` (destroys all containers and rebuilds from scratch) and `ahoy up` which just starts existing containers.

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/working-with-sdp.md
> +- Create a new .pygmy.yml file so haproxy can be configured to another port other than 80
This should go into the troubleshooting document IMO as it's a Cenitex only issue (as it hogs port 80)

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +1. Check if you Open Workspace is in your machine. This will allow software installation that requires elevated permissions.
*Check if Open Workplace is installed on your machine.

Also, a screen shot of the PCInfo app would help here. Ping me if you need help with this.

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +3. Check again to see if you have the elevated permissions or not. You might have restart your computer several times to take effect.
*several times for it it to take effect.

2021-12-15 06:45 UTC, anthony-malkoun commented on docs/troubleshooting.md
> +2. If you believe to have Open Workspace installed but still have issue with installations, logoff from Citrix Gateway (Windows Taskbar Icon) and reconnect through Go Connect (Window search). An IE b
```suggestion
2. If you believe Open Workplace is installed but are still having issues with installations, logoff from Citrix Gateway (Windows Taskbar Icon) and reconnect through Go Connect (Window search). An IE browser will open and ask for your DPC login credentials. Process might take some time to complete or your browser might appear to hang. In that case try restarting your computer and retry Go Connect.
```

2021-12-19 23:05 UTC, anthony-malkoun approved these changes
Thanks for making the requested changes @edyuenyw. Please feel free to merge this in when you get a chance.

2021-12-19 23:42 UTC, merged